name: streamstatus
version: '1.1'
main: uk.vrtxx.streamstatus.Streamstatus
api-version: '1.21'
authors: [ TutorialMan7727 ]
description: Allows users to show if they are streaming/recording
website: https://vrtx.uk
commands:
  streaming:
    description: Toggle your streaming status
    usage: /streaming [on|off]
  recording:
    description: Toggle your recording status
    usage: /recording [on|off]