name: streamstatus
version: "1.1"
main: uk.vrtxx.streamstatus.paper.Streamstatus
api-version: "26.1.2"
authors: [TutorialMan7727]
description: Allows users to show if they are streaming/recording
website: https://vrtxx.uk
commands:
  streaming:
    description: Toggle your streaming status
    usage: /streaming [on|off]
  recording:
    description: Toggle your recording status
    usage: /recording [on|off]
